name: Advent Of Code

on:
  push:
  workflow_call:

jobs:
  advent-of-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Use Node 16
        uses: actions/setup-node@v3.5.1
        cache: 'yarn'
        with:
          node-version: '16'

      - name: Yarn Install
        run: yarn install

      - name: Advent of Code 21
        run: yarn run test
